### ISSUE TITLE
Customize image generation with additional attributes

### ISSUE THREAD

**Issue by yshmarov** [igor-alexandrov/jekyll-og-image#5]
Obviously currently the generated images look very github-like.

It would be cool if we could add a few more variables, like `bg_color` that would override the white background.

Also, at least in my blog, each post has a `thumbnail` variable.

It would be cool if we could have something like `image: %{page.thumbnail} || "/assets/og/logo.jpg"`

**Comment by igor-alexandrov** [comment]
@yshmarov regarding overriding background I propose the following interface to be added.

```
og_image:
  background:
      color: "#CCCCCC"
  header:
    font_family: "Roboto"
    font_color: "#000000"
  content:
    font_family: "Roboto"
    font_color: "#000000"
```

* `background` will handle settings relevant to the image's background. Currently, only a single color will be supported. I plan to add gradients later.
* `header` will handle settings for the header/title. Currently, you can change `font-family` and `font-color`.
* `content` will handle settings for all other text content on the image.

Let me know, what do you think.
